# Generated by Django 6.0.5 on 2026-05-24 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('ID_Departamento', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Departamento', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'departamentos',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('ID_Persona', models.AutoField(primary_key=True, serialize=False)),
                ('Numero_Documento', models.CharField(max_length=50, unique=True)),
                ('Nombres', models.CharField(max_length=150)),
                ('Apellidos', models.CharField(max_length=150)),
                ('Email', models.CharField(blank=True, max_length=150, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('Fecha_Nacimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personas',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('ID_Cargo', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Cargo', models.CharField(max_length=150)),
                ('Descripcion_Funciones', models.CharField(blank=True, max_length=500, null=True)),
                ('Salario_Base', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('Hora_Inicio_Jornada', models.TimeField(blank=True, null=True)),
                ('Hora_Fin_Jornada', models.TimeField(blank=True, null=True)),
                ('ID_Departamento', models.ForeignKey(db_column='ID_Departamento', on_delete=django.db.models.deletion.PROTECT, to='asistencia.departamento')),
            ],
            options={
                'db_table': 'cargos',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('ID_Empleado', models.AutoField(primary_key=True, serialize=False)),
                ('PIN', models.CharField(max_length=6, unique=True)),
                ('Rol', models.CharField(choices=[('admin', 'Administrador'), ('empleado', 'Empleado')], default='empleado', max_length=20)),
                ('Fecha_Ingreso', models.DateField(blank=True, null=True)),
                ('Fecha_Retiro', models.DateField(blank=True, null=True)),
                ('Estado_Empleado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=50)),
                ('ID_Cargo', models.ForeignKey(db_column='ID_Cargo', on_delete=django.db.models.deletion.PROTECT, to='asistencia.cargo')),
                ('ID_Persona', models.ForeignKey(db_column='ID_Persona', on_delete=django.db.models.deletion.PROTECT, to='asistencia.persona')),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('ID_Contrato', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo_Contrato', models.CharField(blank=True, max_length=100, null=True)),
                ('Salario_Pactado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('Fecha_Inicio', models.DateField(blank=True, null=True)),
                ('Fecha_Fin', models.DateField(blank=True, null=True)),
                ('Estado_Contrato', models.CharField(choices=[('Vigente', 'Vigente'), ('Terminado', 'Terminado'), ('Suspendido', 'Suspendido')], default='Vigente', max_length=50)),
                ('ID_Cargo', models.ForeignKey(db_column='ID_Cargo', on_delete=django.db.models.deletion.PROTECT, to='asistencia.cargo')),
                ('ID_Empleado', models.ForeignKey(blank=True, db_column='ID_Empleado', null=True, on_delete=django.db.models.deletion.PROTECT, to='asistencia.empleado')),
            ],
            options={
                'db_table': 'contratos',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('ID_Registro', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Hora_Entrada', models.TimeField()),
                ('Hora_Salida', models.TimeField(blank=True, null=True)),
                ('Tipo', models.CharField(default='Normal', max_length=80)),
                ('Observacion', models.CharField(blank=True, max_length=300, null=True)),
                ('ID_Empleado', models.ForeignKey(db_column='ID_Empleado', on_delete=django.db.models.deletion.PROTECT, to='asistencia.empleado')),
            ],
            options={
                'db_table': 'registros',
            },
        ),
        migrations.CreateModel(
            name='SstAccidente',
            fields=[
                ('ID_Accidente', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Accidente', models.DateField(blank=True, null=True)),
                ('Tipo_Accidente', models.CharField(blank=True, max_length=100, null=True)),
                ('Descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('Accion_Inmediata', models.CharField(blank=True, max_length=500, null=True)),
                ('Fecha_Reporte', models.DateField(blank=True, null=True)),
                ('ID_Empleado', models.ForeignKey(db_column='ID_Empleado', on_delete=django.db.models.deletion.PROTECT, to='asistencia.empleado')),
            ],
            options={
                'db_table': 'sst_accidentes',
            },
        ),
        migrations.CreateModel(
            name='CargoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dia_Semana', models.CharField(max_length=20)),
                ('ID_Cargo', models.ForeignKey(db_column='ID_Cargo', on_delete=django.db.models.deletion.CASCADE, to='asistencia.cargo')),
            ],
            options={
                'db_table': 'cargo_dias',
                'unique_together': {('ID_Cargo', 'Dia_Semana')},
            },
        ),
    ]
